### ISSUE TITLE
Add "colossalai" in requirements

### ISSUE THREAD

**Issue by Yanjia0** [Thecats-Jfm/OpenRLHF#1]
Hi developer~
Glad to see you will be adding ColossalAIChat in the near future. Thank you so much for using Colossal-AI! May I kindly request you to add **colossalai** into your **requirements.txt** file and help our community to expand? 
Thank you! If you need any help when using Colossal-AI, feel free to join our Slack/Wechat group~

**Comment by Thecats-Jfm** [comment]
Thank you for your interest and suggestion! It's important to note that while the main project, `openrlhf`, has indeed referred to various outstanding projects and frameworks, including ColossalChat and others, to enrich the field of AI and NLP, the forked project in question (this project) has not directly utilized Colossal-AI.

The modifications made in this fork are minor and do not involve the integration or use of Colossal-AI. The decision to not include Colossal-AI in the `requirements.txt` file is based on the specific scope and needs of these modifications, which do not align with the addition of new dependencies at this time.

We appreciate the enthusiasm and support for Colossal-AI and its community. We understand the importance of collaboration and acknowledgment within the open-source ecosystem. However, given the nature of the contributions made in this fork, adding Colossal-AI as a dependency does not match the project's current direction or requirements.

We hope this clarification helps, and we remain open to any further suggestions or feedback. Thank you once again for reaching out and for your understanding.
